name: Run Python Script Periodically

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download sequence file
        uses: actions/download-artifact@v3
        with:
          name: sequence-artifact
          path: ./

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version of Python you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl  # Add other dependencies if needed

      - name: Run the script
        run: python main.py

      - name: Upload sequence file
        uses: actions/upload-artifact@v3
        with:
          name: sequence-artifact
          path: email_sequence.txt
